### ISSUE TITLE
Setup "Ask A Book Questions" for Google Colab

### ISSUE THREAD

**Issue by crjaensch** [gkamradt/langchain-tutorials#10]
Hello,
let me first of all say, you have created a great tutorial on how to create a Q&A engine for any pdf-document based knowledge base. I love it!!!
I setup a Google Colab notebook to replicate your tutorial and came across quite a few issues during the environment setup.
The following screenshot shows all setup tasks needed to make it run successfully on Google Colab. I hope other readers find this useful.
<img width="1279" alt="Google Colab Environment Setup" src="https://user-images.githubusercontent.com/6088963/232336587-2fc80ee9-10e9-4fbb-80b0-2562052587e7.png">

**Comment by KoichiroHatsuse** [comment]
This helps a lot!
Thank you.

**Comment by gkamradt** [comment]
Thank you!
