### ISSUE TITLE
pinecone now closed to free users - can you show how to use this with another alt system

### ISSUE THREAD

**Issue by stevedipaola** [gkamradt/langchain-tutorials#11]
They just closed pinecone's free system to now a waiting list ( and it is $70/month for the next level) - can some explain how to get this working with an alternative system to pinecone.

**Comment by startakovsky** [comment]
@stevedipaola So many options, but just to stick to the langchain ecosystem . . . https://python.langchain.com/en/latest/modules/indexes/vectorstores.html

**Comment by gkamradt** [comment]
Agreed, check out more on the integrations page
https://langchain.com/integrations.html
