### ISSUE TITLE
ValidationError: 1 validation error for FewShotPromptTemplate example_selector   instance of BaseExampleSelector expected (type=type_error.arbitrary_type; expected_arbitrary_type=BaseExampleSelector)

### ISSUE THREAD

**Issue by retroradioryan** [gkamradt/langchain-tutorials#14]
Anyone know how I fix this error? 

ValidationError: 1 validation error for FewShotPromptTemplate
example_selector
  instance of BaseExampleSelector expected (type=type_error.arbitrary_type; expected_arbitrary_type=BaseExampleSelector)

**Comment by gkamradt** [comment]
Can you link to the tutorial and code this is coming from?

**Comment by retroradioryan** [comment]
https://github.com/gkamradt/langchain-tutorials/blob/main/LangChain%20Cookbook%20Part%201%20-%20Fundamentals.ipynb
<img width="1203" alt="Screenshot 2023-05-02 at 17 59 31" src="https://user-images.githubusercontent.com/130701554/235734504-801ac6bb-6b63-4c0c-9398-f874b508b661.png">

**Comment by gkamradt** [comment]
I just ran that code no problem. Can you confirm you're on the latest version of langchain?

Version: 0.0.153

**Comment by retroradioryan** [comment]
That was the issue... Thanks!!!
