### ISSUE TITLE
Run 5 levels of summarization-level 3 mapreduce code got an error

### ISSUE THREAD

**Issue by lemondy** [gkamradt/langchain-tutorials#19]
when i run level 3 map reduce code, i got an error like :

```
ValueError: OpenAIChat currently only supports single prompt, got 
```

I think it comes form code:

```
output = summary_chain.run(docs)
```

i have search from the interenet, and still not find a solution, so how can i solved this.

my local environment:

Python 3.9.5 (default, May 18 2021, 12:31:01)
langchain               0.0.167
openai                  0.27.6

**Comment by gkamradt** [comment]
How many docs are in your docs? You may have to wrap it in a list like [docs].
