### ISSUE TITLE
NameError: name 'chain' is not defined

### ISSUE THREAD

**Issue by bbuxton0823** [gkamradt/langchain-tutorials#2]
Hello! I am receiving this NameError after this line: chain.run(input_documents=docs, question=query)

NameError Traceback (most recent call last)
Cell In[32], line 1
----> 1 chain.run(input_documents=docs, question=query)

NameError: name 'chain' is not defined

In GPT4 I get this answer:

The NameError indicates that the interpreter is unable to find a defined variable or function named chain. This error occurs when the name is not defined in the current scope, or there is a typo in the name.

To fix the error, you need to ensure that the variable chain is defined in the current scope. Check to see if you have defined chain earlier in the code or in a different module that you may have forgotten to import.

In some cases, running the cells from the beginning after selecting "Restart & Clear Output" may resolve the issue [[1](https://stackoverflow.com/questions/40407090/nameerror-name-pd-is-not-defined)]. It may also be helpful to review the documentation for the package or module you are using to ensure that you are using it correctly. Checking for any typos in the variable name may also help resolve the issue.

Overall, the NameError indicates that the interpreter is unable to find a defined variable or function. To fix the error, ensure that the name is defined in the current scope or imported from another module, and check for any typos in the name.

**Comment by samuellukudu** [comment]
Import LLMChain; then set chain = LLMChain()
