### ISSUE TITLE
ValidationError: 1 validation error for SQLDatabaseToolkit

### ISSUE THREAD

**Issue by SEUlegend** [gkamradt/langchain-tutorials#21]
I got this error. The version of langchain is 0.0.169. I want to know how to fix this error.

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[2], line 3
      1 # db = SQLDatabase.from_uri("sqlite:///../../../../notebooks/Chinook.db")
      2 db = SQLDatabase.from_uri("sqlite:///../../notebooks/Chinook.db")
----> 3 toolkit = SQLDatabaseToolkit(db=db)
      4 agent_executor = create_sql_agent(
      5     llm = OpenAI(temperature=0, openai_api_key="sk-xxx"),
      6     toolkit=toolkit,
      7     verbose=True
      8 )

File ~/miniconda3/envs/aigc/lib/python3.10/site-packages/pydantic/main.py:342, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for SQLDatabaseToolkit
llm
  field required (type=value_error.missing)

**Comment by SEUlegend** [comment]
Thank you very much. The problem has been solved to put the LLM parameter into the SQLDatabaseToolkit

**Comment by richa1711** [comment]
Can you please write the code. I am also having the same issue.
