### ISSUE TITLE
The class CallbackManager had moved from langchain.callbacks.base to langchain.callbacks.manager 

### ISSUE THREAD

**Issue by sun-shining** [gkamradt/langchain-tutorials#38]
When I ran the code for 'With Streaming' in ChatAPI + LangChain Basics.ipynb, I encountered an error: 'cannot import name 'CallbackManager' from 'langchain.callbacks.base'.'
 Upon further investigation in the LangChain documentation, I discovered that the package containing CallbackManager has been modified.

**Comment by gkamradt** [comment]
Updated!
