### ISSUE TITLE
Feature Request: Add a source/citation

### ISSUE THREAD

**Issue by Olney1** [gkamradt/langchain-tutorials#40]
I know we can print the documents that match the question via Pinecone, but it would be great to be able to print a citation or source that was used to determine the final answer if this can be added as a feature? Great work btw.

**Comment by gkamradt** [comment]
Totally! This is with the question and answer chain w/ sources. Is that what you're asking about?

**Comment by Olney1** [comment]
Ah sorry, been a long day where do I find this?

**Comment by Olney1** [comment]
For anyone wondering the same, see here last block of code: https://github.com/gkamradt/langchain-tutorials/blob/main/data_generation/Custom%20Files%20Question%20%26%20Answer.ipynb
