### ISSUE TITLE
Typo in the Cookbook part 1

### ISSUE THREAD

**Issue by Adithyan777** [gkamradt/langchain-tutorials#43]
Your vectorstore store your embeddings (☝️) and make "the" easily searchable
I guess it should be: "Your vectorstore store your embeddings (☝️) and make "them" easily searchable" :)
Thanks

**Comment by gkamradt** [comment]
Nice thank you! Can you throw up a PR for the quick change?

**Comment by Adithyan777** [comment]
I have submitted a pull request with the quick change to address the typo.
Thanks :)
