### ISSUE TITLE
Which python version does these program run? 

### ISSUE THREAD

**Issue by aadabi** [gkamradt/langchain-tutorials#44]
Would be nice to lock the versions in the Requirement file version, i.e. via Pip freeze because the long chain is changing so much and breaking sometime.

**Comment by aadabi** [comment]
I figure this out basically because my jupyter notebook was running on a different version, just pip install jupyter

**Comment by bhaswata08** [comment]
Python 3.11

**Comment by gkamradt** [comment]
Thank you both - yes this is a known issue and this repo needs a lot of clean up.

The next version will have a requirements file that one can reference
