### ISSUE TITLE
Mongo Loader

### ISSUE THREAD

**Issue by myrulezzz** [gkamradt/langchain-tutorials#5]
Hi. I have a quick question. Do you have any example with the SimpleMongo DB loader? have you tested this connector?
I am finding difficulties to connect on Mongo db with username and password as per documentation is using only host and port. And also can i use the html reader to read a website and using llang agent to store content locally?

**Comment by gkamradt** [comment]
I don't, sorry!

**Comment by gs-rpal** [comment]
Mongo DB type implementation is not supported yet.

**Comment by myrulezzz** [comment]
Hi gs-rpal Came up with this colab https://colab.research.google.com/drive/1SNIeLW38Nvx6MtL3-_LPS2XTIzqD4gS6?usp=sharing 
ofcourse is supported
