### ISSUE TITLE
Additional questions on the summarisation tutorial

### ISSUE THREAD

**Issue by gidzr** [gkamradt/langchain-tutorials#55]
Hey there

Thanks for putting this together. I had the same conclusion regarding the summarisation of a large document, in terms of splitting, then embedding, and then ranking the sections and choosing the most relevant for a map_reduce.

However, I've been scouring the net and racking my brains to find a splitter that would work according to theme (eg. keyword density) or being able to identify chapter/section breaks without having to pre-define what the markup would look like.

Is there a python tool or form of analysis that can segment a text document into smaller part more intelligently than a character length breakpoint?

Thanks :)

**Comment by gkamradt** [comment]
That's a great question and a topic that I've actually been thinking a lot about. I think I might do a tutorial about the 5 levels of text splitting that work for different examples.

I haven't seen yet a "semantic splitter" like you're talking about but it's on my mind.

Good question!
