### ISSUE TITLE
Add 'pip install' step to top of notebooks

### ISSUE THREAD

**Issue by richieM** [gkamradt/langchain-tutorials#56]
It would be helpful to explicitly add a `!pip install langchain openai` cell to the top of the LangChain Cookbooks. Otherwise, users have to play whack-a-mole with installing some packages as they work down the notebook.

**Comment by lebsral** [comment]
and maybe?

%pip install dotenv

**Comment by gkamradt** [comment]
Agree! This is on the list of house keeping updates I'm going to work on towards the end of the month or early next month. Thanks for the heads up
