### ISSUE TITLE
Unclear input and passed variables

### ISSUE THREAD

**Issue by kubasiak** [gkamradt/langchain-tutorials#6]
Hi, I am goint through your email tutorial and one I like it a lot however one thing remains unclear and it is left without any comment. Perhpas it would be good to clarify?

Input variables are 'input_documents', 'company' etc.. but map template uses 'text' as well as reduce template uses 'text' 

Which text is it? is it the same value? I guess not,  but it is not mentioned and actually this is the only part of your code that is leaving me with some  questions. 

Is it recognized by position?

**Comment by gkamradt** [comment]
Ah yes! Good call - It's sort of confusing.

LangChain knows what to do with that text token in the background. It's a system token they use to insert whatever is given in the input documents.

You can see it on this line
https://github.com/hwchase17/langchain/blob/afa9d1292b0a152e36d338dde7b02f0b93bd37d9/langchain/chains/summarize/__init__.py#L45

as well as this one:
https://github.com/hwchase17/langchain/blob/afa9d1292b0a152e36d338dde7b02f0b93bd37d9/langchain/chains/summarize/__init__.py#LL81C32-L81C65

As I'm looking at the documentation now I should have called out this variable explicitly in the code but I didn't and left it hidden.

If you're open to it, can you throw up a PR to call it out explicitly and write it w/ the other chain variables?
